/**
 * Realistic typed mock data for the BANG GA BANG GA prototype.
 * Nothing here talks to a server — every screen reads from this file.
 */

import type {
  Address,
  AdminUser,
  AuditEntry,
  Branch,
  Category,
  Customer,
  OptionGroup,
  Order,
  Product,
  Promotion,
} from "./types";

/* ------------------------------------------------------------------ */
/* Branches — exactly two today, the model supports more               */
/* ------------------------------------------------------------------ */

export const BRANCHES: Branch[] = [
  {
    id: "ss15",
    name: "SS15, Subang Jaya",
    shortName: "SS15",
    address: "12-G, Jalan SS15/4D, SS15",
    city: "Subang Jaya",
    postcode: "47500",
    phone: "+60 3-5612 8840",
    lat: 3.0764,
    lng: 101.5859,
    deliveryRadiusKm: 8,
    supportsDineIn: true,
    supportsPickup: true,
    supportsDelivery: true,
    prepTimeMinutes: 18,
    hours: [
      { day: 1, opens: "11:00", closes: "22:00" },
      { day: 2, opens: "11:00", closes: "22:00" },
      { day: 3, opens: "11:00", closes: "22:00" },
      { day: 4, opens: "11:00", closes: "22:00" },
      { day: 5, opens: "11:00", closes: "23:00" },
      { day: 6, opens: "10:00", closes: "23:00" },
      { day: 7, opens: "10:00", closes: "22:00" },
    ],
    distanceKm: 2.3,
    mapHint: "Opposite the SS15 courtyard, two doors from the bubble tea corner",
  },
  {
    id: "taylors",
    name: "Taylor's Lakeside Campus",
    shortName: "Taylor's Lakeside",
    address: "Level 2, Student Life Centre, 1 Jalan Taylor's",
    city: "Subang Jaya",
    postcode: "47500",
    phone: "+60 3-5629 5117",
    lat: 3.0653,
    lng: 101.6169,
    deliveryRadiusKm: 6,
    supportsDineIn: true,
    supportsPickup: true,
    supportsDelivery: true,
    prepTimeMinutes: 14,
    hours: [
      { day: 1, opens: "10:00", closes: "20:00" },
      { day: 2, opens: "10:00", closes: "20:00" },
      { day: 3, opens: "10:00", closes: "20:00" },
      { day: 4, opens: "10:00", closes: "20:00" },
      { day: 5, opens: "10:00", closes: "21:00" },
      { day: 6, opens: "11:00", closes: "18:00" },
      { day: 7, opens: "11:00", closes: "18:00" },
    ],
    distanceKm: 7.1,
    mapHint: "Inside the Student Life Centre food hall, next to the lake deck",
  },
];

export const branchById = (id: string) => BRANCHES.find((b) => b.id === id) ?? BRANCHES[0];

/* ------------------------------------------------------------------ */
/* Categories                                                          */
/* ------------------------------------------------------------------ */

export const CATEGORIES: Category[] = [
  { id: "signature", name: "Signature Chicken", slug: "signature-chicken", blurb: "Boneless, sauced, seriously good", icon: "chicken" },
  { id: "sets", name: "Individual Sets", slug: "sets", blurb: "Complete meals under RM20", icon: "set" },
  { id: "sharing", name: "Sharing Platters", slug: "sharing", blurb: "Built for a table of friends", icon: "platter" },
  { id: "sides", name: "Sides & Snacks", slug: "sides", blurb: "Tteokbokki, kimbap, fries", icon: "side" },
  { id: "drinks", name: "Drinks", slug: "drinks", blurb: "Korean sodas, teas and yuzu", icon: "drink" },
  { id: "photobooth", name: "Photo Booth", slug: "photo-booth", blurb: "Add a session to your order", icon: "photo" },
];

/* ------------------------------------------------------------------ */
/* Option groups                                                       */
/* ------------------------------------------------------------------ */

export const OPTION_GROUPS: OptionGroup[] = [
  {
    id: "size",
    name: "Size",
    helper: "Choose 1",
    minSelect: 1,
    maxSelect: 1,
    required: true,
    choices: [
      { id: "size-regular", name: "Regular", priceDelta: 0 },
      { id: "size-large", name: "Large", priceDelta: 500, soldOutAt: ["taylors"] },
    ],
  },
  {
    id: "sauce",
    name: "Sauce",
    helper: "Choose 1 — all sauces are Muslim-friendly",
    minSelect: 1,
    maxSelect: 1,
    required: true,
    choices: [
      { id: "sauce-soy", name: "Soy garlic", priceDelta: 0 },
      { id: "sauce-yangnyeom", name: "Yangnyeom sweet & spicy", priceDelta: 0 },
      { id: "sauce-honey", name: "Honey butter", priceDelta: 100 },
      { id: "sauce-gochu", name: "Gochujang extra hot", priceDelta: 100 },
      { id: "sauce-plain", name: "No sauce, seasoning only", priceDelta: 0 },
    ],
  },
  {
    id: "spice",
    name: "Spice level",
    helper: "Optional",
    minSelect: 0,
    maxSelect: 1,
    required: false,
    choices: [
      { id: "spice-mild", name: "Mild", priceDelta: 0 },
      { id: "spice-medium", name: "Medium", priceDelta: 0 },
      { id: "spice-hot", name: "Hot", priceDelta: 0 },
    ],
  },
  {
    id: "addons",
    name: "Add-ons",
    helper: "Up to 3",
    minSelect: 0,
    maxSelect: 3,
    required: false,
    choices: [
      { id: "add-cheese", name: "Mozzarella cheese dip", priceDelta: 300 },
      { id: "add-rice", name: "Steamed rice", priceDelta: 200 },
      { id: "add-egg", name: "Marinated egg", priceDelta: 200 },
      { id: "add-kimchi", name: "House kimchi", priceDelta: 250, soldOutAt: ["ss15"] },
      { id: "add-fries", name: "Seaweed fries", priceDelta: 450 },
    ],
  },
  {
    id: "drinkchoice",
    name: "Drink",
    helper: "Choose 1",
    minSelect: 1,
    maxSelect: 1,
    required: true,
    choices: [
      { id: "drink-yuzu", name: "Yuzu sparkling", priceDelta: 0 },
      { id: "drink-barley", name: "Iced barley tea", priceDelta: 0 },
      { id: "drink-milkis", name: "Milkis soda", priceDelta: 150 },
    ],
  },
  {
    id: "prints",
    name: "Print copies",
    helper: "Choose 1",
    minSelect: 1,
    maxSelect: 1,
    required: true,
    choices: [
      { id: "print-1", name: "1 strip", priceDelta: 0 },
      { id: "print-2", name: "2 strips", priceDelta: 100 },
      { id: "print-4", name: "4 strips", priceDelta: 250 },
    ],
  },
];

export const optionGroupById = (id: string) => OPTION_GROUPS.find((g) => g.id === id);

/* ------------------------------------------------------------------ */
/* Products                                                            */
/* ------------------------------------------------------------------ */

const A = (ss15: Product["availability"][string], taylors: Product["availability"][string]) => ({
  ss15,
  taylors,
});

export const PRODUCTS: Product[] = [
  {
    id: "p-soy",
    slug: "soy-garlic-boneless",
    categoryId: "signature",
    name: "Soy Garlic Boneless Chicken",
    koreanName: "간장 순살치킨",
    description: "Crisp boneless chicken tossed in sweet soy garlic glaze.",
    longDescription:
      "Our house boneless chicken, double-fried for crunch and finished in a sweet soy garlic glaze with toasted sesame. The sauce is made in-house every morning and contains no alcohol or mirin.",
    price: 1600,
    image: "/images/food/soy-garlic-boneless.jpg",
    tags: ["Bestseller", "Boneless"],
    spiceLevel: 0,
    allergens: ["Soy", "Wheat", "Sesame"],
    muslimFriendly: true,
    popular: true,
    signature: true,
    optionGroupIds: ["size", "sauce", "spice", "addons"],
    availability: A("available", "available"),
    promotionId: "promo-student",
    kcal: 620,
  },
  {
    id: "p-yangnyeom",
    slug: "yangnyeom-boneless",
    categoryId: "signature",
    name: "Yangnyeom Boneless Chicken",
    koreanName: "양념 순살치킨",
    description: "Sweet, sticky and gently spicy — the classic Korean red sauce.",
    longDescription:
      "Boneless chicken in yangnyeom sauce: gochujang, honey and garlic cooked down until glossy. Sweet first, warm at the finish. Our most ordered sauce.",
    price: 1800,
    image: "/images/food/yangnyeom-boneless.jpg",
    tags: ["Bestseller", "Spicy"],
    spiceLevel: 2,
    allergens: ["Soy", "Wheat", "Sesame"],
    muslimFriendly: true,
    popular: true,
    signature: true,
    optionGroupIds: ["size", "sauce", "spice", "addons"],
    availability: A("available", "low"),
    kcal: 680,
  },
  {
    id: "p-honeybutter",
    slug: "honey-butter-boneless",
    categoryId: "signature",
    name: "Honey Butter Boneless Chicken",
    koreanName: "허니버터 순살치킨",
    description: "Buttery, sweet and salty. The one kids and first-timers pick.",
    longDescription:
      "Boneless chicken tumbled in honey butter seasoning with a light dusting of milk powder. No heat at all — the safe choice for a table that disagrees about spice.",
    price: 1700,
    image: "/images/food/honey-butter-boneless.jpg",
    tags: ["Mild"],
    spiceLevel: 0,
    allergens: ["Dairy", "Soy", "Wheat"],
    muslimFriendly: true,
    popular: true,
    signature: true,
    optionGroupIds: ["size", "sauce", "addons"],
    availability: A("available", "available"),
    kcal: 710,
  },
  {
    id: "p-gochu",
    slug: "gochujang-fire-boneless",
    categoryId: "signature",
    name: "Gochujang Fire Boneless",
    koreanName: "고추장 순살치킨",
    description: "Our hottest sauce. Order a barley tea with it.",
    longDescription:
      "For people who mean it. Aged gochujang, chilli flake and a touch of honey to keep it edible. We will ask you to confirm before we cook it.",
    price: 1800,
    image: "/images/food/gochujang-fire.jpg",
    tags: ["Extra spicy"],
    spiceLevel: 3,
    allergens: ["Soy", "Wheat", "Sesame"],
    muslimFriendly: true,
    popular: false,
    signature: true,
    optionGroupIds: ["size", "sauce", "spice", "addons"],
    availability: A("available", "available"),
    kcal: 650,
  },
  {
    id: "p-seasoned",
    slug: "original-seasoned-boneless",
    categoryId: "signature",
    name: "Original Seasoned Boneless",
    koreanName: "후라이드 순살치킨",
    description: "No sauce, just the crunch and our seasoning blend.",
    longDescription:
      "The purist order. Boneless chicken, double-fried, seasoned with our house salt, pepper and seaweed blend. Sauces are served on the side so nothing goes soggy.",
    price: 1500,
    image: "/images/food/original-seasoned.jpg",
    tags: ["Classic"],
    spiceLevel: 0,
    allergens: ["Wheat"],
    muslimFriendly: true,
    popular: false,
    signature: true,
    optionGroupIds: ["size", "addons"],
    availability: A("available", "available"),
    kcal: 540,
  },
  {
    id: "p-set-soy",
    slug: "soy-garlic-set",
    categoryId: "sets",
    name: "Soy Garlic Set",
    description: "Boneless chicken, rice, kimchi and a drink. Under RM20.",
    longDescription:
      "A complete lunch for one: soy garlic boneless chicken, steamed rice, house kimchi and your choice of drink. Designed for the class-to-class hour.",
    price: 1890,
    image: "/images/food/soy-garlic-set.jpg",
    tags: ["Under RM20", "Set"],
    spiceLevel: 0,
    allergens: ["Soy", "Wheat", "Sesame"],
    muslimFriendly: true,
    popular: true,
    signature: false,
    optionGroupIds: ["sauce", "drinkchoice", "addons"],
    availability: A("available", "available"),
    promotionId: "promo-lunch",
    kcal: 890,
  },
  {
    id: "p-set-yangnyeom",
    slug: "yangnyeom-set",
    categoryId: "sets",
    name: "Yangnyeom Set",
    description: "Sweet-spicy boneless, rice, pickled radish and a drink.",
    longDescription:
      "Yangnyeom boneless chicken with steamed rice, pickled radish and a drink. Ask for extra sauce — we will not judge.",
    price: 1950,
    image: "/images/food/yangnyeom-set.jpg",
    tags: ["Under RM20", "Set", "Spicy"],
    spiceLevel: 2,
    allergens: ["Soy", "Wheat", "Sesame"],
    muslimFriendly: true,
    popular: true,
    signature: false,
    optionGroupIds: ["sauce", "drinkchoice", "addons"],
    availability: A("available", "available"),
    promotionId: "promo-lunch",
    kcal: 930,
  },
  {
    id: "p-set-tteok",
    slug: "tteokbokki-set",
    categoryId: "sets",
    name: "Tteokbokki Comfort Set",
    description: "Rice cakes, fish-free broth, boneless bites and a drink.",
    longDescription:
      "Chewy rice cakes in our Muslim-friendly gochujang broth with boneless chicken bites, spring onion and a drink. Comfort food, priced for a student budget.",
    price: 1790,
    image: "/images/food/tteokbokki-set.jpg",
    tags: ["Under RM20", "Set"],
    spiceLevel: 2,
    allergens: ["Soy", "Wheat", "Sesame"],
    muslimFriendly: true,
    popular: false,
    signature: false,
    optionGroupIds: ["drinkchoice", "addons"],
    availability: A("low", "available"),
    kcal: 810,
  },
  {
    id: "p-set-cheese",
    slug: "cheese-lovers-set",
    categoryId: "sets",
    name: "Cheese Lover's Set",
    description: "Honey butter boneless, cheese dip, fries and a drink.",
    longDescription:
      "Honey butter boneless chicken with a warm mozzarella dip, seaweed fries and a drink. The set that ends up on everyone's camera roll.",
    price: 1990,
    image: "/images/food/cheese-lovers-set.jpg",
    tags: ["Under RM20", "Set"],
    spiceLevel: 0,
    allergens: ["Dairy", "Soy", "Wheat"],
    muslimFriendly: true,
    popular: true,
    signature: false,
    optionGroupIds: ["drinkchoice", "addons"],
    availability: A("available", "sold_out"),
    kcal: 1040,
  },
  {
    id: "p-platter-friends",
    slug: "friends-platter",
    categoryId: "sharing",
    name: "Friends Platter",
    description: "Two sauces, rice cakes, fries and four drinks. Serves 3–4.",
    longDescription:
      "Two full portions of boneless chicken in sauces of your choice, tteokbokki, seaweed fries and four drinks. The table order for a group that cannot agree.",
    price: 8900,
    image: "/images/food/friends-platter.jpg",
    tags: ["Sharing", "Serves 3–4"],
    spiceLevel: 1,
    allergens: ["Soy", "Wheat", "Sesame", "Dairy"],
    muslimFriendly: true,
    popular: true,
    signature: false,
    optionGroupIds: ["sauce", "addons"],
    availability: A("available", "available"),
    promotionId: "promo-weekend",
    kcal: 2680,
  },
  {
    id: "p-platter-family",
    slug: "family-feast",
    categoryId: "sharing",
    name: "Family Feast",
    description: "Three sauces, sides, rice and six drinks. Serves 5–6.",
    longDescription:
      "Three portions of boneless chicken, tteokbokki, kimbap, steamed rice and six drinks. Call the branch if you want it ready for a specific time.",
    price: 13900,
    image: "/images/food/family-feast.jpg",
    tags: ["Sharing", "Serves 5–6"],
    spiceLevel: 1,
    allergens: ["Soy", "Wheat", "Sesame", "Egg"],
    muslimFriendly: true,
    popular: false,
    signature: false,
    optionGroupIds: ["sauce", "addons"],
    availability: A("available", "available"),
    kcal: 4120,
  },
  {
    id: "p-tteokbokki",
    slug: "cheese-tteokbokki",
    categoryId: "sides",
    name: "Cheese Tteokbokki",
    koreanName: "치즈 떡볶이",
    description: "Chewy rice cakes under a blanket of melted mozzarella.",
    longDescription:
      "Rice cakes simmered in our gochujang broth, finished with mozzarella and torched until it blisters. Made without fish stock.",
    price: 1400,
    image: "/images/food/cheese-tteokbokki.jpg",
    tags: ["Popular"],
    spiceLevel: 2,
    allergens: ["Dairy", "Soy", "Wheat"],
    muslimFriendly: true,
    popular: true,
    signature: false,
    optionGroupIds: ["spice"],
    availability: A("sold_out", "available"),
    kcal: 620,
  },
  {
    id: "p-kimbap",
    slug: "chicken-kimbap",
    categoryId: "sides",
    name: "Chicken Kimbap",
    koreanName: "김밥",
    description: "Eight pieces, rolled to order with boneless chicken.",
    longDescription:
      "Seaweed rice rolls with boneless chicken, pickled radish, carrot and egg. Rolled when you order, so give it a few extra minutes.",
    price: 1200,
    image: "/images/food/chicken-kimbap.jpg",
    tags: [],
    spiceLevel: 0,
    allergens: ["Egg", "Sesame", "Soy"],
    muslimFriendly: true,
    popular: false,
    signature: false,
    optionGroupIds: [],
    availability: A("available", "available"),
    kcal: 480,
  },
  {
    id: "p-fries",
    slug: "seaweed-fries",
    categoryId: "sides",
    name: "Seaweed Fries",
    description: "Skin-on fries with seaweed salt and yuzu mayo.",
    longDescription:
      "Thick-cut skin-on fries dusted with roasted seaweed salt, served with yuzu mayo on the side.",
    price: 900,
    image: "/images/food/seaweed-fries.jpg",
    tags: [],
    spiceLevel: 0,
    allergens: ["Egg", "Soy"],
    muslimFriendly: true,
    popular: true,
    signature: false,
    optionGroupIds: [],
    availability: A("available", "available"),
    kcal: 430,
  },
  {
    id: "p-corndog",
    slug: "mozzarella-corn-dog",
    categoryId: "sides",
    name: "Mozzarella Corn Dog",
    koreanName: "핫도그",
    description: "The cheese pull everyone films. Chicken and mozzarella.",
    longDescription:
      "Half chicken sausage, half mozzarella, rolled in sugar the way Korean street stalls do it. Best eaten within about a minute of collection.",
    price: 850,
    image: "/images/food/mozzarella-corn-dog.jpg",
    tags: ["Street food"],
    spiceLevel: 0,
    allergens: ["Dairy", "Wheat", "Egg"],
    muslimFriendly: true,
    popular: true,
    signature: false,
    optionGroupIds: [],
    availability: A("low", "available"),
    kcal: 390,
  },
  {
    id: "p-kimchi",
    slug: "house-kimchi",
    categoryId: "sides",
    name: "House Kimchi",
    description: "Fermented in-house, no fish sauce, no shrimp paste.",
    longDescription:
      "Napa cabbage kimchi fermented on site using a vegetarian base — no fish sauce and no shrimp paste — so everyone at the table can share it.",
    price: 500,
    image: "/images/food/house-kimchi.jpg",
    tags: ["Muslim-friendly"],
    spiceLevel: 1,
    allergens: [],
    muslimFriendly: true,
    popular: false,
    signature: false,
    optionGroupIds: [],
    availability: A("available", "low"),
    kcal: 60,
  },
  {
    id: "p-yuzu",
    slug: "yuzu-sparkling",
    categoryId: "drinks",
    name: "Yuzu Sparkling",
    description: "Citrus, cold, cuts through the sauce.",
    longDescription: "Sparkling water with house yuzu syrup and a wedge of lime.",
    price: 750,
    image: "/images/food/yuzu-sparkling.jpg",
    tags: [],
    spiceLevel: 0,
    allergens: [],
    muslimFriendly: true,
    popular: true,
    signature: false,
    optionGroupIds: [],
    availability: A("available", "available"),
    kcal: 110,
  },
  {
    id: "p-barley",
    slug: "iced-barley-tea",
    categoryId: "drinks",
    name: "Iced Barley Tea",
    koreanName: "보리차",
    description: "Free refills when you dine in.",
    longDescription: "Roasted barley tea, brewed daily and served over ice. Unsweetened.",
    price: 450,
    image: "/images/food/iced-barley-tea.jpg",
    tags: ["Free refill in-store"],
    spiceLevel: 0,
    allergens: ["Wheat"],
    muslimFriendly: true,
    popular: false,
    signature: false,
    optionGroupIds: [],
    availability: A("available", "available"),
    kcal: 10,
  },
  {
    id: "p-milkis",
    slug: "milkis-soda",
    categoryId: "drinks",
    name: "Milkis Soda",
    description: "Creamy Korean soda, chilled.",
    longDescription: "The classic Korean milk soda, served in the can with ice on the side.",
    price: 600,
    image: "/images/food/milkis-soda.jpg",
    tags: [],
    spiceLevel: 0,
    allergens: ["Dairy"],
    muslimFriendly: true,
    popular: false,
    signature: false,
    optionGroupIds: [],
    availability: A("available", "sold_out"),
    kcal: 150,
  },
  {
    id: "p-strawberry",
    slug: "strawberry-milk",
    categoryId: "drinks",
    name: "Korean Strawberry Milk",
    description: "Crushed strawberries, cold milk, no syrup.",
    longDescription: "Fresh crushed strawberries layered with cold milk. Stir before drinking.",
    price: 950,
    image: "/images/food/strawberry-milk.jpg",
    tags: ["New"],
    spiceLevel: 0,
    allergens: ["Dairy"],
    muslimFriendly: true,
    popular: true,
    signature: false,
    optionGroupIds: [],
    availability: A("available", "available"),
    kcal: 220,
  },
  {
    id: "p-booth-session",
    slug: "photo-booth-session",
    categoryId: "photobooth",
    name: "Photo Booth Session",
    description: "From RM1. Add it now, use it after your meal.",
    longDescription:
      "One photo booth session at the branch you are ordering from. Add it to your order and show the receipt at the booth. Sessions from RM1, extra strips priced below.",
    price: 100,
    image: "/images/food/photo-booth-session.jpg",
    tags: ["From RM1", "MAKE IT LAST"],
    spiceLevel: 0,
    allergens: [],
    muslimFriendly: true,
    popular: true,
    signature: false,
    optionGroupIds: ["prints"],
    availability: A("available", "available"),
    kcal: 0,
  },
  {
    id: "p-booth-frame",
    slug: "photo-strip-frame",
    categoryId: "photobooth",
    name: "Photo Strip Frame",
    description: "Take the strip home in a card frame.",
    longDescription:
      "A printed card frame for your photo strip, in cream or teal. Collect it at the counter with your order.",
    price: 400,
    image: "/images/food/photo-strip-frame.jpg",
    tags: ["MAKE IT LAST"],
    spiceLevel: 0,
    allergens: [],
    muslimFriendly: true,
    popular: false,
    signature: false,
    optionGroupIds: [],
    availability: A("available", "available"),
    kcal: 0,
  },
];

export const productById = (id: string) => PRODUCTS.find((p) => p.id === id);
export const productBySlug = (slug: string) => PRODUCTS.find((p) => p.slug === slug);

/* ------------------------------------------------------------------ */
/* Promotions                                                          */
/* ------------------------------------------------------------------ */

export const PROMOTIONS: Promotion[] = [
  {
    id: "promo-student",
    code: "STUDENT10",
    name: "Student Wednesday",
    badge: "10% OFF",
    description: "10% off signature chicken every Wednesday with a valid student ID.",
    type: "percentage",
    value: 10,
    minSpend: 1500,
    branchIds: ["ss15", "taylors"],
    endsOn: "2026-12-31",
    terms: [
      "Valid on Wednesdays only, all day.",
      "Show a valid student ID at pickup or to the rider.",
      "One redemption per order. Cannot be combined with Lunch Rush.",
    ],
  },
  {
    id: "promo-lunch",
    code: "LUNCH5",
    name: "Lunch Rush",
    badge: "RM5 OFF SETS",
    description: "RM5 off any individual set between 11am and 2pm on weekdays.",
    type: "fixed",
    value: 500,
    minSpend: 1500,
    branchIds: ["ss15", "taylors"],
    endsOn: "2026-10-31",
    terms: [
      "Weekdays 11:00–14:00 only.",
      "Applies to Individual Sets category.",
      "Minimum spend RM15 before delivery fee.",
    ],
  },
  {
    id: "promo-weekend",
    code: "FREEDEL",
    name: "Weekend Free Delivery",
    badge: "FREE DELIVERY",
    description: "Free delivery on sharing platters over RM80, Saturday and Sunday.",
    type: "free_delivery",
    value: 0,
    minSpend: 8000,
    branchIds: ["ss15"],
    endsOn: "2026-11-30",
    terms: [
      "SS15 branch only.",
      "Delivery address must be within 8 km.",
      "Weekend orders only.",
    ],
  },
  {
    id: "promo-booth",
    name: "Meal + Booth",
    badge: "RM1 BOOTH",
    description: "Add a photo booth session for RM1 with any set or platter.",
    type: "bundle",
    value: 100,
    minSpend: 1700,
    branchIds: ["ss15", "taylors"],
    endsOn: "2026-12-31",
    terms: [
      "One RM1 session per order.",
      "Session must be used on the same day at the same branch.",
      "Extra print strips charged separately.",
    ],
  },
];

export const promotionById = (id?: string) =>
  id ? PROMOTIONS.find((p) => p.id === id) : undefined;

/* ------------------------------------------------------------------ */
/* Customer account mock                                               */
/* ------------------------------------------------------------------ */

export const MOCK_USER = {
  id: "u-aisyah",
  name: "Aisyah Rahman",
  email: "aisyah.r@example.com",
  phone: "+60 12-345 6789",
  joinedOn: "2025-03-14",
  loyaltyStrips: 7,
};

export const SAVED_ADDRESSES: Address[] = [
  {
    id: "addr-home",
    label: "Home",
    line1: "12 Jalan SS15/4",
    line2: "Blok B, Unit 8-3",
    city: "Subang Jaya",
    postcode: "47500",
    state: "Selangor",
    notes: "Gate code 1234, leave at the guardhouse if nobody answers",
    isDefault: true,
  },
  {
    id: "addr-campus",
    label: "Campus",
    line1: "Taylor's Lakeside Campus",
    line2: "Block D, Student Life Centre",
    city: "Subang Jaya",
    postcode: "47500",
    state: "Selangor",
    isDefault: false,
  },
  {
    id: "addr-office",
    label: "Office",
    line1: "Menara Sunway, Jalan Lagoon Timur",
    line2: "Level 14",
    city: "Bandar Sunway",
    postcode: "47500",
    state: "Selangor",
    notes: "Call on arrival, reception will collect",
    isDefault: false,
  },
];

/* ------------------------------------------------------------------ */
/* Orders — one per interesting status, for admin + history screens    */
/* ------------------------------------------------------------------ */

const line = (
  productId: string,
  quantity: number,
  options: CartLineOptionSeed[] = [],
  notes?: string,
): Order["lines"][number] => {
  const p = productById(productId)!;
  return {
    lineId: `${productId}-${quantity}-${options.map((o) => o.choiceId).join("-")}`,
    productId,
    name: p.name,
    image: p.image,
    unitPrice: p.price + options.reduce((s, o) => s + o.priceDelta, 0),
    quantity,
    options: options.map((o) => ({
      groupId: o.groupId,
      groupName: o.groupName,
      choiceId: o.choiceId,
      choiceName: o.choiceName,
      priceDelta: o.priceDelta,
    })),
    notes,
  };
};

type CartLineOptionSeed = {
  groupId: string;
  groupName: string;
  choiceId: string;
  choiceName: string;
  priceDelta: number;
};

const SOY_LARGE: CartLineOptionSeed[] = [
  { groupId: "size", groupName: "Size", choiceId: "size-large", choiceName: "Large", priceDelta: 500 },
  { groupId: "sauce", groupName: "Sauce", choiceId: "sauce-soy", choiceName: "Soy garlic", priceDelta: 0 },
  { groupId: "addons", groupName: "Add-ons", choiceId: "add-cheese", choiceName: "Mozzarella cheese dip", priceDelta: 300 },
];

const SET_SOY: CartLineOptionSeed[] = [
  { groupId: "sauce", groupName: "Sauce", choiceId: "sauce-soy", choiceName: "Soy garlic", priceDelta: 0 },
  { groupId: "drinkchoice", groupName: "Drink", choiceId: "drink-barley", choiceName: "Iced barley tea", priceDelta: 0 },
];

export const MOCK_ORDERS: Order[] = [
  {
    id: "o-0138",
    code: "BG-260921-0138",
    customerName: "Aisyah Rahman",
    customerPhone: "+60 12-345 6789",
    customerEmail: "aisyah.r@example.com",
    isGuest: false,
    branchId: "ss15",
    fulfilment: "delivery",
    address: SAVED_ADDRESSES[0],
    lines: [line("p-soy", 2, SOY_LARGE, "Less spicy please"), line("p-tteokbokki", 1)],
    subtotal: 5200,
    discount: 500,
    deliveryFee: 650,
    tax: 250,
    total: 5600,
    status: "WAITING_FOR_BRANCH",
    placedAt: "2026-09-21T19:02:00+08:00",
    branchSlaSeconds: 300,
    promotionCode: "STUDENT10",
    customerNotes: "Gate code 1234",
    payment: {
      method: "visa",
      provider: "Maybank",
      status: "paid",
      amount: 5600,
      reference: "MBB-TXN-9F2A4C71",
      maskedCard: "•••• 4242",
      paidAt: "2026-09-21T19:02:41+08:00",
    },
    delivery: { provider: "Lalamove", fee: 650, status: "not_booked" },
    events: [
      { status: "PENDING_PAYMENT", label: "Order created", at: "19:02", actor: "customer" },
      { status: "PAID", label: "Payment received · Maybank", at: "19:02", actor: "system" },
      { status: "WAITING_FOR_BRANCH", label: "Sent to SS15", at: "19:02", actor: "system" },
    ],
  },
  {
    id: "o-0137",
    code: "BG-260921-0137",
    customerName: "Wei Jie Tan",
    customerPhone: "+60 16-220 7781",
    isGuest: true,
    branchId: "ss15",
    fulfilment: "pickup",
    lines: [line("p-set-yangnyeom", 1, SET_SOY)],
    subtotal: 1950,
    discount: 0,
    deliveryFee: 0,
    tax: 117,
    total: 2067,
    status: "PREPARING",
    placedAt: "2026-09-21T18:55:00+08:00",
    branchSlaSeconds: 300,
    payment: {
      method: "duitnow_qr",
      provider: "OXPay",
      status: "paid",
      amount: 2067,
      reference: "OXP-QR-5512B803",
      paidAt: "2026-09-21T18:55:52+08:00",
    },
    events: [
      { status: "PAID", label: "Payment received · OXPay", at: "18:55", actor: "system" },
      { status: "ACCEPTED", label: "Accepted by SS15", at: "18:57", actor: "branch" },
      { status: "PREPARING", label: "Kitchen started", at: "18:58", actor: "kitchen" },
    ],
  },
  {
    id: "o-0136",
    code: "BG-260921-0136",
    customerName: "Kumar Devaraj",
    customerPhone: "+60 19-887 4410",
    isGuest: false,
    branchId: "taylors",
    fulfilment: "delivery",
    address: SAVED_ADDRESSES[2],
    lines: [line("p-platter-friends", 1), line("p-fries", 2)],
    subtotal: 10700,
    discount: 0,
    deliveryFee: 0,
    tax: 642,
    total: 11342,
    status: "OUT_FOR_DELIVERY",
    placedAt: "2026-09-21T18:31:00+08:00",
    branchSlaSeconds: 300,
    promotionCode: "FREEDEL",
    payment: {
      method: "visa",
      provider: "Maybank",
      status: "paid",
      amount: 11342,
      reference: "MBB-TXN-1D77E902",
      maskedCard: "•••• 7714",
      paidAt: "2026-09-21T18:31:33+08:00",
    },
    delivery: {
      provider: "Lalamove",
      quotationId: "LLM-Q-7741",
      bookingId: "LLM-B-55120",
      fee: 720,
      status: "delivering",
      riderName: "Ahmad Faizal",
      riderPhone: "+60 13-662 8890",
      riderVehicle: "Yamaha NMAX",
      riderPlate: "WXY 1234",
      etaMinutes: 9,
    },
    events: [
      { status: "PAID", label: "Payment received · Maybank", at: "18:31", actor: "system" },
      { status: "ACCEPTED", label: "Accepted by Taylor's Lakeside", at: "18:33", actor: "branch" },
      { status: "PREPARING", label: "Kitchen started", at: "18:34", actor: "kitchen" },
      { status: "READY", label: "Ready for collection", at: "18:52", actor: "kitchen" },
      { status: "LALAMOVE_BOOKED", label: "Lalamove booked", at: "18:53", actor: "branch" },
      { status: "RIDER_PICKED_UP", label: "Ahmad picked up the order", at: "19:01", actor: "rider" },
      { status: "OUT_FOR_DELIVERY", label: "On the way", at: "19:02", actor: "rider" },
    ],
  },
  {
    id: "o-0135",
    code: "BG-260921-0135",
    customerName: "Sarah Lim",
    customerPhone: "+60 17-330 2255",
    isGuest: false,
    branchId: "ss15",
    fulfilment: "delivery",
    address: SAVED_ADDRESSES[0],
    lines: [line("p-set-cheese", 2)],
    subtotal: 3980,
    discount: 0,
    deliveryFee: 650,
    tax: 239,
    total: 4869,
    status: "REFUND_PENDING",
    placedAt: "2026-09-21T18:12:00+08:00",
    branchSlaSeconds: 300,
    rejectionReason: "An item is unavailable right now",
    payment: {
      method: "visa",
      provider: "Maybank",
      status: "refund_pending",
      amount: 4869,
      reference: "MBB-TXN-4410CC28",
      maskedCard: "•••• 1902",
      paidAt: "2026-09-21T18:12:19+08:00",
      refundReference: "MBB-RF-8842",
      refundRequestedAt: "2026-09-21T18:16:04+08:00",
      refundNote: "Reversal submitted to Maybank. Completion depends on the issuing bank.",
    },
    events: [
      { status: "PAID", label: "Payment received · Maybank", at: "18:12", actor: "system" },
      { status: "WAITING_FOR_BRANCH", label: "Sent to SS15", at: "18:12", actor: "system" },
      { status: "REJECTED", label: "Rejected — item unavailable", at: "18:16", actor: "branch" },
      { status: "REFUND_PENDING", label: "Refund initiated · MBB-RF-8842", at: "18:16", actor: "system" },
    ],
  },
  {
    id: "o-0134",
    code: "BG-260921-0134",
    customerName: "Nurul Izzah",
    customerPhone: "+60 11-2277 4400",
    isGuest: true,
    branchId: "taylors",
    fulfilment: "pickup",
    lines: [line("p-corndog", 3), line("p-strawberry", 2)],
    subtotal: 4450,
    discount: 0,
    deliveryFee: 0,
    tax: 267,
    total: 4717,
    status: "REFUND_PENDING",
    placedAt: "2026-09-21T17:40:00+08:00",
    branchSlaSeconds: 300,
    rejectionReason: "Branch did not respond within 5 minutes (prototype rule)",
    payment: {
      method: "duitnow_qr",
      provider: "OXPay",
      status: "manual_refund_required",
      amount: 4717,
      reference: "OXP-QR-99B21D40",
      paidAt: "2026-09-21T17:40:38+08:00",
      refundReference: "OXP-RF-PENDING",
      refundRequestedAt: "2026-09-21T17:45:38+08:00",
      manualRefundReason:
        "OXPay DuitNow QR does not support automated reversal for this transaction type. Finance must refund manually and record the bank reference.",
    },
    events: [
      { status: "PAID", label: "Payment received · OXPay", at: "17:40", actor: "system" },
      { status: "WAITING_FOR_BRANCH", label: "Sent to Taylor's Lakeside", at: "17:40", actor: "system" },
      { status: "REJECTED", label: "Auto-rejected — no branch response in 5 min", at: "17:45", actor: "system" },
      { status: "REFUND_PENDING", label: "Manual refund required", at: "17:45", actor: "system" },
    ],
  },
  {
    id: "o-0133",
    code: "BG-260920-0133",
    customerName: "Aisyah Rahman",
    customerPhone: "+60 12-345 6789",
    isGuest: false,
    branchId: "ss15",
    fulfilment: "delivery",
    address: SAVED_ADDRESSES[0],
    lines: [line("p-yangnyeom", 1, SOY_LARGE), line("p-fries", 1), line("p-yuzu", 2)],
    subtotal: 4550,
    discount: 0,
    deliveryFee: 650,
    tax: 273,
    total: 5473,
    status: "COMPLETED",
    placedAt: "2026-09-20T19:20:00+08:00",
    branchSlaSeconds: 300,
    payment: {
      method: "visa",
      provider: "Maybank",
      status: "paid",
      amount: 5473,
      reference: "MBB-TXN-77C10A55",
      maskedCard: "•••• 4242",
      paidAt: "2026-09-20T19:20:29+08:00",
    },
    delivery: {
      provider: "Lalamove",
      quotationId: "LLM-Q-7612",
      bookingId: "LLM-B-54980",
      fee: 650,
      status: "delivered",
      riderName: "Siva Kumar",
      riderPhone: "+60 12-908 7765",
      riderVehicle: "Honda RS150",
      riderPlate: "VBA 8821",
    },
    events: [
      { status: "PAID", label: "Payment received · Maybank", at: "19:20", actor: "system" },
      { status: "ACCEPTED", label: "Accepted by SS15", at: "19:22", actor: "branch" },
      { status: "PREPARING", label: "Kitchen started", at: "19:23", actor: "kitchen" },
      { status: "READY", label: "Ready", at: "19:41", actor: "kitchen" },
      { status: "OUT_FOR_DELIVERY", label: "On the way", at: "19:48", actor: "rider" },
      { status: "DELIVERED", label: "Delivered", at: "20:04", actor: "rider" },
      { status: "COMPLETED", label: "Order completed", at: "20:04", actor: "system" },
    ],
  },
  {
    id: "o-0132",
    code: "BG-260920-0132",
    customerName: "Aisyah Rahman",
    customerPhone: "+60 12-345 6789",
    isGuest: false,
    branchId: "taylors",
    fulfilment: "pickup",
    lines: [line("p-set-soy", 1, SET_SOY), line("p-booth-session", 1)],
    subtotal: 1990,
    discount: 500,
    deliveryFee: 0,
    tax: 89,
    total: 1579,
    status: "COMPLETED",
    placedAt: "2026-09-18T12:40:00+08:00",
    branchSlaSeconds: 300,
    promotionCode: "LUNCH5",
    payment: {
      method: "duitnow_qr",
      provider: "OXPay",
      status: "refunded",
      amount: 1579,
      reference: "OXP-QR-2277AA10",
      paidAt: "2026-09-18T12:40:44+08:00",
      refundReference: "OXP-RF-1180",
      refundRequestedAt: "2026-09-18T13:02:00+08:00",
      refundCompletedAt: "2026-09-19T10:14:00+08:00",
      refundNote: "Partial refund for the photo booth session — booth was under maintenance.",
    },
    events: [
      { status: "PAID", label: "Payment received · OXPay", at: "12:40", actor: "system" },
      { status: "ACCEPTED", label: "Accepted", at: "12:41", actor: "branch" },
      { status: "READY", label: "Ready for pickup", at: "12:53", actor: "kitchen" },
      { status: "COMPLETED", label: "Collected", at: "12:58", actor: "branch" },
      { status: "REFUNDED", label: "Partial refund completed", at: "10:14", actor: "system" },
    ],
  },
  {
    id: "o-0131",
    code: "BG-260921-0131",
    customerName: "Daniel Foo",
    customerPhone: "+60 18-661 2093",
    isGuest: true,
    branchId: "ss15",
    fulfilment: "delivery",
    address: SAVED_ADDRESSES[1],
    lines: [line("p-honeybutter", 1, SOY_LARGE)],
    subtotal: 2500,
    discount: 0,
    deliveryFee: 650,
    tax: 150,
    total: 3300,
    status: "FAILED",
    placedAt: "2026-09-21T17:05:00+08:00",
    branchSlaSeconds: 300,
    payment: {
      method: "visa",
      provider: "Maybank",
      status: "paid",
      amount: 3300,
      reference: "MBB-TXN-3390FF12",
      maskedCard: "•••• 3310",
      paidAt: "2026-09-21T17:05:12+08:00",
    },
    delivery: {
      provider: "Lalamove",
      quotationId: "LLM-Q-7588",
      bookingId: "LLM-B-54871",
      fee: 650,
      status: "failed",
      failureReason: "No rider accepted the booking within 12 minutes",
    },
    events: [
      { status: "PAID", label: "Payment received · Maybank", at: "17:05", actor: "system" },
      { status: "ACCEPTED", label: "Accepted by SS15", at: "17:06", actor: "branch" },
      { status: "READY", label: "Ready", at: "17:24", actor: "kitchen" },
      { status: "LALAMOVE_BOOKED", label: "Lalamove booked", at: "17:25", actor: "branch" },
      { status: "FAILED", label: "No rider found — needs action", at: "17:37", actor: "system" },
    ],
  },
  {
    id: "o-0130",
    code: "BG-260921-0130",
    customerName: "Mei Ling Chow",
    customerPhone: "+60 12-771 4432",
    isGuest: false,
    branchId: "taylors",
    fulfilment: "pickup",
    lines: [line("p-kimbap", 2), line("p-barley", 2)],
    subtotal: 3300,
    discount: 0,
    deliveryFee: 0,
    tax: 198,
    total: 3498,
    status: "READY",
    placedAt: "2026-09-21T18:44:00+08:00",
    branchSlaSeconds: 300,
    payment: {
      method: "duitnow_qr",
      provider: "OXPay",
      status: "paid",
      amount: 3498,
      reference: "OXP-QR-6631CD07",
      paidAt: "2026-09-21T18:44:20+08:00",
    },
    events: [
      { status: "PAID", label: "Payment received · OXPay", at: "18:44", actor: "system" },
      { status: "ACCEPTED", label: "Accepted", at: "18:45", actor: "branch" },
      { status: "PREPARING", label: "Kitchen started", at: "18:46", actor: "kitchen" },
      { status: "READY", label: "Ready for pickup", at: "19:00", actor: "kitchen" },
    ],
  },
  {
    id: "o-0129",
    code: "BG-260921-0129",
    customerName: "Hafiz Zainal",
    customerPhone: "+60 13-556 9921",
    isGuest: true,
    branchId: "ss15",
    fulfilment: "delivery",
    address: SAVED_ADDRESSES[0],
    lines: [line("p-set-tteok", 1, [SET_SOY[1]])],
    subtotal: 1790,
    discount: 0,
    deliveryFee: 650,
    tax: 107,
    total: 2547,
    status: "PENDING_PAYMENT",
    placedAt: "2026-09-21T19:06:00+08:00",
    branchSlaSeconds: 300,
    payment: {
      method: "duitnow_qr",
      provider: "OXPay",
      status: "unpaid",
      amount: 2547,
      reference: "OXP-QR-PENDING-0129",
    },
    events: [{ status: "PENDING_PAYMENT", label: "Order created", at: "19:06", actor: "customer" }],
  },
];

/* ------------------------------------------------------------------ */
/* Admin data                                                          */
/* ------------------------------------------------------------------ */

export const CUSTOMERS: Customer[] = [
  { id: "c-1", name: "Aisyah Rahman", phone: "+60 12-345 6789", email: "aisyah.r@example.com", joinedOn: "2025-03-14", orderCount: 34, lifetimeSpend: 128940, favouriteBranchId: "ss15", tags: ["Regular", "Student"] },
  { id: "c-2", name: "Kumar Devaraj", phone: "+60 19-887 4410", email: "kumar.d@example.com", joinedOn: "2025-07-02", orderCount: 19, lifetimeSpend: 97210, favouriteBranchId: "taylors", tags: ["Group orders"] },
  { id: "c-3", name: "Sarah Lim", phone: "+60 17-330 2255", email: "sarah.lim@example.com", joinedOn: "2026-01-19", orderCount: 8, lifetimeSpend: 31240, favouriteBranchId: "ss15", tags: [] },
  { id: "c-4", name: "Wei Jie Tan", phone: "+60 16-220 7781", email: "weijie@example.com", joinedOn: "2026-04-08", orderCount: 5, lifetimeSpend: 11035, favouriteBranchId: "ss15", tags: ["Guest checkout"] },
  { id: "c-5", name: "Nurul Izzah", phone: "+60 11-2277 4400", email: "nurul.i@example.com", joinedOn: "2026-06-21", orderCount: 3, lifetimeSpend: 8890, favouriteBranchId: "taylors", tags: ["Student"] },
  { id: "c-6", name: "Mei Ling Chow", phone: "+60 12-771 4432", email: "meiling@example.com", joinedOn: "2025-11-30", orderCount: 22, lifetimeSpend: 74380, favouriteBranchId: "taylors", tags: ["Regular"] },
];

export const ADMIN_USERS: AdminUser[] = [
  { id: "a-1", name: "Aisyah Nordin", email: "aisyah@bangga.my", role: "Super Admin", branchId: null, lastActive: "2 min ago", active: true },
  { id: "a-2", name: "Jun Ho Park", email: "junho@bangga.my", role: "Branch Manager", branchId: "ss15", lastActive: "just now", active: true },
  { id: "a-3", name: "Farah Yusof", email: "farah@bangga.my", role: "Branch Staff", branchId: "ss15", lastActive: "6 min ago", active: true },
  { id: "a-4", name: "Ravi Menon", email: "ravi@bangga.my", role: "Branch Manager", branchId: "taylors", lastActive: "18 min ago", active: true },
  { id: "a-5", name: "Chef Lee", email: "kitchen.ss15@bangga.my", role: "Kitchen", branchId: "ss15", lastActive: "just now", active: true },
  { id: "a-6", name: "Chef Amir", email: "kitchen.tlc@bangga.my", role: "Kitchen", branchId: "taylors", lastActive: "1 min ago", active: true },
  { id: "a-7", name: "Grace Tan", email: "finance@bangga.my", role: "Finance", branchId: null, lastActive: "2 hours ago", active: true },
  { id: "a-8", name: "Idris Hassan", email: "idris@bangga.my", role: "Branch Staff", branchId: "taylors", lastActive: "3 days ago", active: false },
];

export const AUDIT_LOG: AuditEntry[] = [
  { id: "al-1", at: "21 Sep 19:02", actor: "System", role: "Super Admin", action: "payment.captured", entity: "BG-260921-0138", detail: "Maybank MBB-TXN-9F2A4C71 · RM56.00" },
  { id: "al-2", at: "21 Sep 18:57", actor: "Jun Ho Park", role: "Branch Manager", action: "order.accepted", entity: "BG-260921-0137", detail: "Accepted at SS15, prep time 14 min" },
  { id: "al-3", at: "21 Sep 18:53", actor: "Ravi Menon", role: "Branch Manager", action: "delivery.booked", entity: "BG-260921-0136", detail: "Lalamove LLM-B-55120 · RM7.20" },
  { id: "al-4", at: "21 Sep 18:16", actor: "Farah Yusof", role: "Branch Staff", action: "order.rejected", entity: "BG-260921-0135", detail: "Reason: item unavailable · refund MBB-RF-8842 initiated" },
  { id: "al-5", at: "21 Sep 17:45", actor: "System", role: "Super Admin", action: "order.auto_rejected", entity: "BG-260921-0134", detail: "No branch response within 300s (prototype rule)" },
  { id: "al-6", at: "21 Sep 17:37", actor: "System", role: "Super Admin", action: "delivery.failed", entity: "BG-260921-0131", detail: "Lalamove: no rider accepted within 12 min" },
  { id: "al-7", at: "21 Sep 16:20", actor: "Aisyah Nordin", role: "Super Admin", action: "menu.price_updated", entity: "Yangnyeom Boneless Chicken", detail: "RM17.00 → RM18.00 at both branches" },
  { id: "al-8", at: "21 Sep 15:02", actor: "Chef Lee", role: "Kitchen", action: "inventory.sold_out", entity: "Cheese Tteokbokki · SS15", detail: "Marked sold out for the rest of the day" },
  { id: "al-9", at: "21 Sep 11:30", actor: "Grace Tan", role: "Finance", action: "refund.manual_recorded", entity: "BG-260918-0112", detail: "Bank reference MB-778213 · RM23.40" },
  { id: "al-10", at: "20 Sep 22:14", actor: "Aisyah Nordin", role: "Super Admin", action: "admin.role_changed", entity: "Idris Hassan", detail: "Branch Staff deactivated" },
];

/* ------------------------------------------------------------------ */
/* Dashboard figures                                                   */
/* ------------------------------------------------------------------ */

export const DASHBOARD = {
  revenueToday: 428050,
  ordersToday: 68,
  waiting: 1,
  preparing: 3,
  avgOrder: 6295,
  ordersByHour: [
    { hour: "11", ss15: 3, taylors: 2 },
    { hour: "12", ss15: 9, taylors: 7 },
    { hour: "13", ss15: 7, taylors: 5 },
    { hour: "14", ss15: 3, taylors: 2 },
    { hour: "15", ss15: 2, taylors: 1 },
    { hour: "16", ss15: 2, taylors: 2 },
    { hour: "17", ss15: 4, taylors: 3 },
    { hour: "18", ss15: 8, taylors: 4 },
    { hour: "19", ss15: 6, taylors: 3 },
  ],
  revenueByBranch: [
    { branchId: "ss15", label: "SS15", amount: 268400 },
    { branchId: "taylors", label: "Taylor's Lakeside", amount: 159650 },
  ],
  topProducts: [
    { name: "Soy Garlic Boneless Chicken", units: 41, revenue: 68900 },
    { name: "Yangnyeom Set", units: 28, revenue: 54600 },
    { name: "Cheese Tteokbokki", units: 24, revenue: 33600 },
    { name: "Mozzarella Corn Dog", units: 22, revenue: 18700 },
    { name: "Photo Booth Session", units: 19, revenue: 3800 },
  ],
};

/* ------------------------------------------------------------------ */
/* Prototype-only copy                                                 */
/* ------------------------------------------------------------------ */

export const PROTOTYPE_RULES = {
  branchSlaSeconds: 300,
  branchSlaLabel: "Prototype business rule: the branch has 5 minutes to accept or the order is auto-rejected and refunded.",
  refundTimingLabel:
    "Refund completion time depends on the payment provider and the customer's bank. Maybank card reversals typically settle in 3–5 working days; DuitNow QR refunds may require a manual bank transfer.",
  cancelBeforePayment: "You can cancel this order any time before payment is completed.",
  cancelAfterConfirm:
    "This order is already being prepared. Please contact the branch for assistance.",
};
